### ISSUE TITLE
I can't identify the difference between these two queries!

### ISSUE THREAD

**Issue by behrad** [mjodeh/chabok-job-offer#1]
https://github.com/mjodeh/chabok-job-offer/blob/101349df6d2618f9ca224a84b9c2c904d3f4f2a0/src/database/database.js#L31-L40

**Comment by mjodeh** [comment]
`select * from chabokJob.chabokjob inner join (select id from chabokJob.chabokjob inner join (select id from chabokJob.chabokjob where name='Purchase') as temp on temp.id=chabokjob.id where name='Search') as u on u.id=chabokjob.id`

Fixed!

**Comment by behrad** [comment]
How is the results reported in readme related to the wrong code?
